name: Push actions

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'
      - 'README.md'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions: 
      contents: write
      packages: write 
    steps:
      # get repo code
      - uses: actions/checkout@v2
      # install node
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
          registry-url: 'https://registry.npmjs.org'
      # install packages
      - run: yarn --frozen-lockfile
      # run checksum test
      - run: yarn checksum
      # transpile from Typescript to Javascript
      - run: yarn compile
      # bump package version and commit. Note that this won't create an infinite github action push loop, as we have added package.json to paths-ignore.
      - uses: tool3/bump@v1.1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
      # publish package
      - run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}